AMQP_URI: 'pyamqp://guest:guest@localhost' # Connection to RabbitMQ
rpc_exchange: 'nameko-rpc'
REDIS_URL: 'redis://localhost:6379/0'
DB_URIS:
  user_service:Base:
    "postgresql+psycopg2://postgres:secret@localhost/users?client_encoding=utf8"